# Generated by Django 2.2.4 on 2019-09-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_type',
            field=models.CharField(default='veg', max_length=10),
        ),
    ]
