# Generated by Django 2.2.7 on 2020-03-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Failed', max_length=100),
        ),
    ]
